server:
  port: 8080

spring:
  datasource :
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:prography
    username: sa
    password:
  jpa:
    open-in-view: false
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create
  h2:
    console:
      enabled: true
      path: /h2-console

faker:
  api-url: "https://fakerapi.it/api/v1/users?_seed=%d&_quantity=%d&_locale=ko_KR"

game:
  duration-ms: 60000 # 60초

room:
  max-capacity:
    single: 2
    multi: 4

user-status:
  active-threshold: 30
  wait-threshold: 60
